### ISSUE TITLE
Improve CSS of Flash Messages.

### ISSUE THREAD

**Issue by saurabhshri** [saurabhshri/ccextractor-web#12]
Looks like our flash messages need some CSS work. :)

![screenshot 2018-10-29 at 7 33 05 pm](https://user-images.githubusercontent.com/12415700/47654763-8f9e2300-dbb1-11e8-9fff-13eabcb7af2a.png)

**Comment by saurabhshri** [comment]
Relevant section of code : https://github.com/saurabhshri/ccextractor-web/blob/development/templates/_formHelper.html#L56

**Comment by arc9693** [comment]
Here too.<br>

![screenshot from 2018-11-13 17-04-33](https://user-images.githubusercontent.com/36061892/48413175-ee949800-e76c-11e8-9e8d-2c20663da69b.png)

<br>

I would like to work on this.
Can you brief me on how you want the messages to be displayed?
Just the correct spacing or positioning as well?

@saurabhshri

**Comment by saurabhshri** [comment]
Thank you for showing interest, @arc9693 . You're right, the messages in forms could also use some CSS improvements. :)

For flash messages, currently they are appended to each other instead of appearing one below the other. Also, I think it would be a great idea if those messages do not append to the webpage body, but sorts of overlays (i.e. drops down from top, or slide in from side) above the page. Maybe something like :

![screenshot 2018-11-13 at 6 23 07 pm](https://user-images.githubusercontent.com/12415700/48414702-71b7ed00-e771-11e8-8325-89bbc4d8e730.png)

For form messages, proper alignment, positioning and spacing should do it.

Having said that, feel free to choose (for both) what you think is best.  As long as it's fixed and appealing, I am happy with it :)
