### ISSUE TITLE
Create 'admin' user when initialising the app irrespective of application 'mode'.

### ISSUE THREAD

**Issue by saurabhshri** [saurabhshri/ccextractor-web#13]
Currently admin account is created only when initialising app in 'local mode'. Create an admin account when initialising app irrespective of application 'mode'.

Relevant section of code: https://github.com/saurabhshri/ccextractor-web/blob/61d78ca7d08b6b26742476f2e9eb71b4b7ea274c/run.py#L52

Relevant config : https://github.com/saurabhshri/ccextractor-web/blob/61d78ca7d08b6b26742476f2e9eb71b4b7ea274c/instance/config.py#L172

**Comment by T1duS** [comment]
After fixing it, how can I test if it works in public mode? @saurabhshri

**Comment by saurabhshri** [comment]
@T1duS By running the app in 'public mode'. See: https://github.com/saurabhshri/ccextractor-web/blob/development/docs/installation.adoc#local-vs-public-instance
