### ISSUE TITLE
 File "run.py", line 12, in <module>

### ISSUE THREAD

**Issue by JoxtaQrst** [saurabhshri/ccextractor-web#16]
I have this problem when i try to run python3 run.py:
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    from flask import Flask, g, session, render_template
ModuleNotFoundError: No module named 'flask'

**Comment by T1duS** [comment]
Try doing sudo python3 -m pip install -r requirements.txt before running.

**Comment by JoxtaQrst** [comment]
Now i get this error:
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    from config_parser import general_config
  File "/home/joxta1129/ccextractor-web/config_parser.py", line 11, in <module>
    from config import app_config
  File "/home/joxta1129/ccextractor-web/config.py", line 64
    LOG_FILE_DIR = logs/
                       ^
SyntaxError: invalid syntax

**Comment by JoxtaQrst** [comment]
Now it get this wrong , and i don't know why:
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    from config_parser import general_config
  File "/home/joxta1129/ccextractor-web/config_parser.py", line 11, in <module>
    from config import app_config
  File "/home/joxta1129/ccextractor-web/config.py", line 64
    LOG_FILE_DIR = /home/joxta1129/ccextractor-web/logs
                   ^
SyntaxError: invalid syntax

**Comment by T1duS** [comment]
@JoxtaQrst can u show your config.py and instance/config.py files?

**Comment by JoxtaQrst** [comment]
[files.zip](https://github.com/saurabhshri/ccextractor-web/files/2601151/files.zip)

**Comment by T1duS** [comment]
Your file path should be enclosed with (' ') or (" ") as they are strings.

**Comment by JoxtaQrst** [comment]
What about the Log_Level?

**Comment by T1duS** [comment]
that should also be enclosed with (' ') or (" ") as given in the example - "DEBUG"

**Comment by JoxtaQrst** [comment]
Sorry to disturb you, but now i have this problem:
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from mod_kvm.controller import mod_kvm
  File "/home/joxta1129/ccextractor-web/mod_kvm/controller.py", line 19, in <module>
    from mod_kvm.models import KVM, VM, kvm_log
  File "/home/joxta1129/ccextractor-web/mod_kvm/models.py", line 11, in <module>
    import libvirt
ModuleNotFoundError: No module named 'libvirt

**Comment by T1duS** [comment]
try sudo apt install libvirt-dev

**Comment by JoxtaQrst** [comment]
Nope. Still the same.

**Comment by T1duS** [comment]
Try this - https://www.linuxquestions.org/questions/slackware-14/virt-manager-fails-to-start-with-importerror-no-module-named-libvirt-4175559586/

**Comment by JoxtaQrst** [comment]
Unfortunately, i still get the same error..

**Comment by saurabhshri** [comment]
@JoxtaQrst Have you checked if your platform supports KVM? 

BTW - you could also run CCExtractor-Web without KVM support (which needs libvirt).  Check-out the config file and docs.

**Comment by JoxtaQrst** [comment]
Thank you for trying to help me

**Comment by saurabhshri** [comment]
Feel free to re-open this issue if it's still any problem.
