### ISSUE TITLE
Syntax Error on Line 52

### ISSUE THREAD

**Issue by doamatto** [saurabhshri/ccextractor-web#17]
When trying to boot this up, it crashes reporting the following:
```
File "run.py", line 52
    def init_app() -> bool:
                          ^
SyntaxError: invalid syntax
```

I am gonna' personally look to see if I can't fix it myself: but, regardless, I'll make the issue

**Comment by canihavesomecoffee** [comment]
Most likely you run an older version of Python which does not support typing (introduced in Python 3.5). Which version of Python do you use?

**Comment by doamatto** [comment]
I'm currently running Python 2.7; I'll update it when I get the chance and
let you know if anything has changed

On 22 Nov 2018 00:14, "Willem" <notifications@github.com> wrote:

Most likely you run an older version of Python which does not support
typing (introduced in Python 3.5). Which version of Python do you use?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/saurabhshri/ccextractor-web/issues/17#issuecomment-440947189>,
or mute the thread

**Comment by doamatto** [comment]
I just updated to sideload both Python2.7 with the command `python27` and Python3.7 with `python37`, along with their compiled pip and other misc. files. The issue now is it seems it doesn't know where the module named 'encodings' that is needed for this is. Gonna' make sure my env. variables are set properly and probably try a fresh install of Python 3.7

**Comment by doamatto** [comment]
I seemed to have fixed it by installing `libvirt-dev` on my rig. Thanks regardless
